### ISSUE TITLE
StyleGuide - Do not declare providers in the bootstrap

### ISSUE THREAD

**Issue by johnpapa** [angular/angular.io#1152]
*To be discussed ... *

I copied several of these from early discussions and will list them as issues for future discussion after ngConf

cc // @mgechev @wardbell

* Do not declare global providers in the [`bootstrap`](https://angular.io/docs/ts/latest/api/platform/browser/bootstrap-function.html) call, use a top-level component instead.

  *Why?*: The providers registered in the [`bootstrap`](https://angular.io/docs/ts/latest/api/platform/browser/bootstrap-function.html) method are meant for overriding existing providers rather than declaring dependencies.

  *Why?*: Because you'll have to redefine these providers again in most of the tests. it's better if you define the providers on the AppComponent.

**Comment by zoechi** [comment]
This is a topic that causes lots of confusion. I found it easier for people to distinguish between global providers (registered in `bootstrap()`) and providers registered on components. 
The suggestion in the current docs leads for example devs to register them on all components which breaks for example routing when `ROUTER_PROVIDERS` are added to other components than the root component (which seems to be especially confusing because `ROUTER_DIRECTIVES` are required on every component where they are used) and of course breaks everything that should be shared among several components.

I don't argue to change this rule, only to make it extra clear what the differences are between

- providers registered in `bootstrap()`
- providers registered **only** on the root component 
- providers registered on shared parents which may or may not be the root component

Ensure there are good examples.

**Comment by johnpapa** [comment]
There will be styles on how to think about providing ... but more importantly, I think a cookbook makes sense for this instead. It's less a style to know where you provide than it is a strategy. 

So I agree this content is needed in depth, but think that belongs in the cookbooks. @wardbell do you  already have one in the works we can link to???

For the style guide see #1165

**Comment by zoechi** [comment]
I see. That's fine of course. Just please be cautious to not cause any more confusion. Lots of questions on StackOverflow are because this is misunderstood and I got the suspicion this is because of the hint in the docs to not add providers to `bootstrap()` but instead to the root component.

**Comment by johnpapa** [comment]
Yep.

Something to keep in mind ... this will be a style guide, not "how angular works". They will be in concert, recommending styles that follow good practices. But details must be in the docs. In other words, the audience for the guide are folks who want to know which choice to make when there are multiple. The audience for the devgide and cookbooks are for folks who want more details on how to do things.

Subtle difference, but it is important. It is what keeps the guide readable and digestible. The guide should suggest a good technique, then point to the docs for depth.

If you find things are not clear when it is published, you can always make a PR.

Thanks for the feedback

**Comment by IgorMinar** [comment]
why: because you'll have to redefine these providers again in most of the tests. it's better if you define the providers on the AppComponent.

**Comment by johnpapa** [comment]
I'll add this. Thanks.

**Comment by wardbell** [comment]
@igorminar Really?

I have not discovered any such advantage when testing. I rarely test the AppComponenf  and therefore anything I would have provided there I must explicitly re-provide for tests of the components that are actually worth testing.

I like the rule for reasons explained elsewhere but I do not grasp this particular reason.

**Comment by zoechi** [comment]
`provide(PLATFORM_DIRECTIVES, {useValue: [CloseContentPanelDirective], multi: true})` seems not to work on the root component but works in `bootstrap()` (http://stackoverflow.com/questions/37560817/using-directives-in-child-components-of-an-angular-2-application/37560885#37560885)  
Such exceptions would need to be explained.
