### ISSUE TITLE
(Question) Developer Guide | Testing

### ISSUE THREAD

**Issue by maximedupre** [angular/angular.io#1388]
The testing page (https://angular.io/docs/ts/latest/guide/testing.html) is a WIP and I really need this information!! Is there a branch that has a more complete version of this tutorial. I don't care if it's a draft/incomplete, I'd be happy with any more information that I can get. If not, I'll wait patiently.

Thanks!

**Comment by wardbell** [comment]
Thanks for the encouragement. I'd recommend the [samples in the repo](https://github.com/angular/angular.io/tree/master/public/docs/_examples/testing/ts/app) but I haven't had a chance to bring them up to RC yet. They're close.  See what you can make of them.

We do intend to bring the whole chapter current soon.

I'm closing because there is nothing more specific we can do here.

Thanks for your patience.
