### ISSUE TITLE
Some people don't like the "blk" code highlight style

### ISSUE THREAD

**Issue by kwalrath** [angular/angular.io#140]
I've been using `<span class="blk">` to subtly highlight user-entered commands, such as in the first black box in the [Dart quickstart](https://angular.io/docs/dart/latest/quickstart.html) (e.g. "mkdir hello_world").

@rkirov doesn't like the look of the black on dark grey, as he remarked in [this discussion](https://github.com/angular/angular.io/pull/133#discussion_r31458430). This is a followup, in hopes that a designer will take a look.

**Comment by mahonnaise** [comment]
As I mentioned in #144, the regular code snippets shouldn't be bold. Now bold + fixed pitch could be used to signify user input. Those O'Reilly books (JavaScript Design Patterns etc) also use this convention.

![angular2-sh1](https://cloud.githubusercontent.com/assets/533423/8017278/ec36297a-0bf1-11e5-8d25-793c03cc7166.png)

Additionally, generated content could be used to to append " ↲" (`content: ' \21b5';`) in comment color.

![angular2-sh2](https://cloud.githubusercontent.com/assets/533423/8017281/f207f78e-0bf1-11e5-810b-395a2fbe73a4.png)

I also muted the '>' on the left, because they aren't important.

And, for comparison, here is now it currently looks:

![angular2-sh0](https://cloud.githubusercontent.com/assets/533423/8017321/aedcd6c2-0bf2-11e5-9edc-a7491f1d6ac5.png)

**Comment by chalin** [comment]
@kwalrath : all but two occurrences of the 'blk' span have been eliminated, and I suggest that the remaining two be dropped as well. Part of the justification for doing so is to make it easier for readers to just copy-and-paste the command (without have to edit out the leading ">" and any given sample command output.

**Comment by Foxandxss** [comment]
What is the status of this now that we have new design?

**Comment by chalin** [comment]
Uses of `blk` have been eliminated (as suggested in an earlier comment).
