### ISSUE TITLE
Feature (discussion): The Angular 2 Quickstart and Tutorial should use angular-cli

### ISSUE THREAD

**Issue by hannahhoward** [angular/angular.io#1454]
In my opinion, the biggest obstacle to adopting Angular 2 (aside from it still being not final) remains the setup step. As compared to Angular 1, the first page on simply getting an Angular 2 project running (Quickstart -- https://angular.io/docs/ts/latest/quickstart.html) is somewhat epic, and I can't imagine easy for a new developer to grasp.

Although it's still in beta, the angular-cli project already offers a much faster way to get up and running with Angular 2, and a much more pleasant development experience as you go. I think it's time for the Angular team to embrace this project as the default way to start an Angular 2 project.

You can already see a sample of what this could look like in this scotch.io article: https://scotch.io/tutorials/use-the-angular-cli-for-faster-angular-2-projects

Obviously this would be a big change so I wanted to create this issue for discussion.

**Comment by Foxandxss** [comment]
All of that is on the way, you don't have to worry about that.

**Comment by hannahhoward** [comment]
Awesome great... wasn't sure if there was hesitation cause angular-cli is still in beta. :)

**Comment by filipeaguiar** [comment]
I kind of disagree on this. Angular 2 is a different beast from Angular 1, so I kinda like the step-by-step approach.

Sure, angular-cli does all the heavy lifting (at least most of it), but is nice to see that you can do it by yourself. And see what's being done behind the curtain.

**Comment by wardbell** [comment]
We will continue to support the non-linear approach in its own cookbook. We agree that it is valuable to understand how it can work without the cli. Moreover, there will be many who _cannot_ use the cli because of certain CLI requirements that they can't meet.

That said, we are moving judiciously toward CLI-based documentation because that is/will be the smoothest learning path and, for most, the most productive path.
