### ISSUE TITLE
Style Guide - Shorter suffix names

### ISSUE THREAD

**Issue by shairez** [angular/angular.io#1470]
Searched for a discussion about this but couldn't find any, so I'm opening this issue - 

I had thoughts about limiting the the file name suffix to up to 4 letters.

**Examples:**

- `hero.comp.ts`
- `hero.spec.ts`
- `hero.srv.ts`
- `pipe.pipe.ts` :)

I've been using this convention for the past 3 years and I think that shorter names are cleaner and less noisy, when you open up a folder to see its files, especially when you have long component names.

And since the component will probably be the most repeating in Angular 2, I think `.comp` is a good short convention for it, as I can't think about another thing that'll collide with it.

@johnpapa - I opened this issue up to hear your and others thoughts about what you think are the pros in writing the full `component` suffix and why did you choose this way?

Thanks!

**Comment by wardbell** [comment]
Perfectly reasonable alternative convention... as most are.

We are on an anti-abbreviation kick in recent years. I think we'll stick with the long words. But the point.ay be worth repeating: pick a naming convention and stuck with it

**Comment by shairez** [comment]
Sure, raising it here because it's a naming convention I think will benefit everyone.

Just wanted to know the reasoning behind your choice

So from what I'm getting is that it's the - anti-abbreviation kick in recent years.

**Comment by johnpapa** [comment]
Abbreviations don't always translate. Some can have multiple meanings. Sometimes people use multiple abbreviations too. Tooling makes it easy and the readability is significant. 
That said of someone wants an abbrev and is consistent I say go for it. Like any guideline, the why and consistency are paramount. 


John Papa




On Sun, May 22, 2016 at 9:47 AM -0700, "Shai Reznik" <notifications@github.com> wrote:












Sure, raising it here because it's a naming convention I think will benefit everyone.



Just wanted to know the reasoning behind your choice



So from what I'm getting is that it's the - anti-abbreviation kick in recent years.

**Comment by shairez** [comment]
OK, so if people ask me, I'll tell them it's because we don't know what'll come in the future and we wanna make it future safe by saying `component` and not `comp` because it might be `composite` or whatever (which are unlikely now, but you never know what will be added)

Cool thanks @wardbell & @johnpapa for your answers

**Comment by Foxandxss** [comment]
The problem with this kind of conventions is that you need to pick one and that is the one that made most sense for us. That doesn't mean that the other conventions are wrong or not as good as the selected one.

The idea is to pick one for your project and stick with it.

**Comment by johnpapa** [comment]
Yep. 
And Shai ... Srv? Serv? Svc? Pip? Pipe? Model? Mod? MDL?
It's just a convention and though some claim it's such a problem to type I think knits a fair trade off. Especially since tooling makes it easy and we type it once then read it 1000s of times. 
:)

John Papa




On Sun, May 22, 2016 at 10:37 AM -0700, "Jesús Rodríguez" <notifications@github.com> wrote:












The problem with this kind of conventions is that you need to pick one and that is the one that made most sense for us. That doesn't mean that the other conventions are wrong or not as good as the selected one.



The idea is to pick one for your project and stick with it.

**Comment by shairez** [comment]
@Foxandxss I don't think it's a problem. It's a good thing IMO to make a choice, even if it means the other aren't wrong. Consistency is obvious when working on an existing large project, but if I'm starting a new one, I have the option to start fresh. 

What I love about this style guide is the "why" section of each choice.
That particular one didn't have one, so I opened up this issue.

And @johnpapa , of course it should be `srv`, there's no other option :stuck_out_tongue_winking_eye:

But I understand your point John, and that is exactly the answer I was looking for.

Thanks!

**Comment by Foxandxss** [comment]
I see al they "why" in there. Tell me what you think that could be improved and I will.

**Comment by johnpapa** [comment]
I agree we should add more to the why. Good point Shai

John Papa




On Sun, May 22, 2016 at 1:30 PM -0700, "Jesús Rodríguez" <notifications@github.com> wrote:












I see al they "why" in there. Tell me what you think that could be improved and I will.

**Comment by shairez** [comment]
Thanks @Foxandxss !

I've created this - 
https://github.com/angular/angular.io/pull/1473

Let me know if it sounds acceptable to you

**Comment by wardbell** [comment]
Closed by pr #1473
