### ISSUE TITLE
Incorrect Documentation: Installing Typings

### ISSUE THREAD

**Issue by ndcunningham** [angular/angular.io#1555]
Basically when i try to install typings using the follow command found on
`npm run typings -- install dt~jasmine --save --global`
[TypeScript Config](https://angular.io/docs/ts/latest/guide/typescript-configuration.html)

We get the following error

> typings ERR! message Unable to find "dt~jasmine" ("npm") in the registry. Did you want to try searching another source?

etc...

**Fix**
In order to fix this issue it should be only

There should only be `typings install dt~jasmine --save --global`

I assume that other relating info on this install should also be updated!
Example:
`npm run typings list`

`npm run typings install`

_Drop the NPM Run_

* **Environment:**

* **Angular version:** 2.0.0-R.C-1

**Comment by Foxandxss** [comment]
The `-- foo bar baz` that is to add more params to the command.

If `npm run typings` executes  `./node_modules/.bin/typings`, by doing `npm run typings -- install foo` you are actually doing `./node_mobules/.bin/typings install foo`.

So anything that can be used with a command, can be used with `npm run` as well.

The issue here I guess is that you are not using `typings 1.x` (which made a breaking change and the way of installation changed). In fact, you can read that the problem here is that it doesn't find the lib, not that it is not recognizing the command.

![](http://puu.sh/pcHtS/a0336eb092.png)

I am closing this.
