### ISSUE TITLE
Incorrect NgFor Documentation

### ISSUE THREAD

**Issue by marvinscharle** [angular/angular.io#1588]
The [documentation page for NgFor](https://angular.io/docs/ts/latest/api/common/NgFor-directive.html) is currently pointing to an old file version (Beta 17).

This means there are incorrect statements about NgFor's syntax:

```
<li *ngFor="let item of items; #i = index">...</li>
<li template="ngFor #item of items; #i = index">...</li>
<template ngFor #item [ngForOf]="items" #i="index"><li>...</li></template>
```

How to reach the page: Google, 2nd result

Correct page is https://angular.io/docs/ts/latest/api/common/index/NgFor-directive.html

**Comment by wardbell** [comment]
Please post to angular, not angular.io

**Comment by pkozlowski-opensource** [comment]
@wardbell content in the master repo is correct, see https://github.com/angular/angular/blob/b160ada5d10fadb53d00bac4919807ee21fc3e59/modules/%40angular/common/src/directives/ng_for.ts#L71-L73 and the generated doc: https://angular.io/docs/ts/latest/api/common/index/NgFor-directive.html

The problem in this issue is that somehow another, old (?) page (https://angular.io/docs/ts/latest/api/common/NgFor-directive.html) published as well (plus possibly links to this page) and this old page has incorrect content. 

In any case I don't think we should have **2 pages** with the documentation for NgFor as we've got today:
* https://angular.io/docs/ts/latest/api/common/NgFor-directive.html (outdated)
* https://angular.io/docs/ts/latest/api/common/index/NgFor-directive.html (correct one)

Please re-open.

**Comment by Foxandxss** [comment]
I realized what the problem is, we will fix it soon. Thanks.
