### ISSUE TITLE
Terminology for decorators/annotations

### ISSUE THREAD

**Issue by billccn** [angular/angular.io#162]
The official TypeScript terminology for the `@thingy` is "decorator"; however, the Angular team seems to refer to it as annotation. This is likely to cause some confusion.

Better align with the correct terminology or make a note in the documentation?

**Comment by PascalPrecht** [comment]
@billccn that's correct. The interesting point here is that, an annotation is really something that depends on how you define it. Because, what is an annotation? Well, an annotation can be anything that annotates something. Like comments in HTML or CSS code. Or decorators in ES7/TS.

Technically those things are decorators, but on a meta level they are annotations as well, since you're using them to annotate your code. However, on the other hand, the decorators provided by Angular 2 specificly **do** create annotations. Where as the annotation is really just the `annotations` and `params` property on a component.

So to be semantically correct: If you write code in ES7/TS, you use decorators. The things that Angular's decorators create are annotations. Long story short, we us decorators that create annotations.

On a meta level decorators are annotations too.

I think that's also what we should clarify on the website. For more details, I've written an article about exactly that here: http://blog.thoughtram.io/angular/2015/05/03/the-difference-between-annotations-and-decorators.html

**Comment by wardbell** [comment]
See the glossary where this is addressed.
