### ISSUE TITLE
Quickstart should have a step to add styles.css

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#1684]
Although this is really tangential to the quickstart, we should have a step where we add it so the user doesn't get an error.

migrated issue from https://github.com/angular/angular/issues/9307 @fadiwissa

---

Current behavior
The quick start guide is missing the Styles.css file. This file is referenced but no where in the "walkthrough" is it described. I got it from the Plunker version of the demo.

Expected/desired behavior
The Styles.css file should be created as one of the steps of the walkthrough.

Reproduction of the problem
Just walk through the walkthrough steps and the browser will throw an error due to its inability to find the referenced Styles.css file (referenced in Index.html)

What is the expected behavior?
The file should simply exist and no error should be thrown.

**Comment by filipesilva** [comment]
@naomiblack I see a section regarding adding styles in the quickstart: https://angular.io/docs/ts/latest/quickstart.html#!#add-some-style. 

It seems to have been there since May 13, introduced on https://github.com/angular/angular.io/commit/6ca1ac2c45a26bb7857e94a6dc92b669c1ecc6db.

**Comment by fadiwissa** [comment]
I should have been more specific; the issue exists in the JavaScript version of the walkthrough. That's where the styles.css step is missing.

On Sun, Jun 19, 2016 at 2:24 AM, Filipe Silva < notifications@github.com [notifications@github.com] > wrote:
@naomiblack [https://github.com/naomiblack] I see a section regarding adding styles in the quickstart: https://angular.io/docs/ts/latest/quickstart.html#!#add-some-style [https://angular.io/docs/ts/latest/quickstart.html#!#add-some-style] .

It seems to have been there since May 13, introduced on 6ca1ac2 [https://github.com/angular/angular.io/commit/6ca1ac2c45a26bb7857e94a6dc92b669c1ecc6db] .

**Comment by filipesilva** [comment]
@fadiwissa right you are, I only checked the TS one. 

#1699 should fix it. Thanks for finding this!
