### ISSUE TITLE
Query Parameters example in document

### ISSUE THREAD

**Issue by maxisam** [angular/angular.io#1743]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In document [ROUTING & NAVIGATION](https://angular.io/docs/ts/latest/guide/router.html#!#query-parameters)

if you run the example and click on Crisis Center > Dragon Burning Cities > hit "Save"

It doesn't highlight anything

**Expected/desired behavior**

 it should come back to Crisis Center and highlight "Dragon Burning Cities"

[Here](http://plnkr.co/edit/GZAD7mRVdgSBlOz1S8hc?p=preview) is my version of example

I changed this line in **app/crisis-center/crisis-detail.component.ts**

` this.router.navigate(['/crisis-center', {id: crisisId, foo: 'foo'}]);`

to 

` this.router.navigate(['/crisis-center'], {queryParams:{id: crisisId, foo: 'foo'}});`

and in **app/crisis-center/crisis-list.component.ts change**

`this.route.params.subscribe` to `this.router.routerState.queryParams` in 

Do I understand this correctly ? Since this section is talking about query parameters, I wonder we should use it instead of route parameter ? 

* **Angular version:** 2.0.0-rc.3

* **Browser:** Chrome 50

* **Language:** TypeScript 1.8

**Comment by Foxandxss** [comment]
Let's ping @brandonroberts

**Comment by brandonroberts** [comment]
The section is talking about query parameters and route parameter. In the transition from the crisis center to the crisis list, we are demonstrating query parameters on a per-route basis which are matrix parameters. There is a bug in that the router where it doesn't pass the parameters to the empty path route `CrisisList` which is why its not selected when navigating back.

**Comment by maxisam** [comment]
so you mean query parameters on a per-route basis doesn't use queryParams syntax ?

not like this `this.router.navigate(['/crisis-center'], {queryParams:{id: crisisId, foo: 'foo'}});` ?

**Comment by brandonroberts** [comment]
@maxisam no. Query parameters are available to all routes. Route parameters are specific to each route. You can have both with no collisions.

Query parameters
`this.router.navigate(['/crisis-center'], { queryParams: {id: crisisId, foo: 'foo' } });`

Route Parameters
`this.router.navigate(['/crisis-center', { id: crisisId, foo: 'foo' }]);`

Both
`this.router.navigate(['/crisis-center', { id: crisisId, foo: 'foo' }, { queryParams: { id: crisisId, foo: 'foo' }]);`

**Comment by maxisam** [comment]
@brandonroberts I understand we can use both at the same time. 

I just don't understand what do you mean by "query parameters on a per-route basis"

Do you mean the example code should be 

`this.router.navigate(['/crisis-center'], {queryParams:{id: crisisId, foo: 'foo'}});`

from the original example, I thought it is using route parameter, not query parameter.

or you were trying to show **route** parameter on a per-route basis ?

**Comment by wardbell** [comment]
We will get these distinctions into docs. We're just behind.

See also this stackoverflow: http://stackoverflow.com/questions/38242584/clear-all-queryparams-with-new-router-v3-angular2/38415980

@maxisam No we should not write `this.router.navigate(['/crisis-center'], {queryParams:{id: crisisId, foo: 'foo'}});`. Brandon was just contrasting examples.

FWIW, the bug that prevented highlighting appears to be fixed in the latest builds. No need to change the sample's `navigate` call.
