### ISSUE TITLE
Router: Break up developer guide into multiple chapters

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular.io#1881]
The router chapter is huge. This issues begins the discussion of how to better organize the router developer guide into beginner/advanced sections.

Proposed topics for beginner chapter
- [x] Initial Setup (Base HREF, Imports, *.routes.ts files)
- [x] Basic Configuration
- [x] Child route configuration
- [x] Router Outlet
- [x] Router Links
- [x] Active Router Links / Options
- [x] Route Data
- [x] Route Params getting/setting
- [x] Query Params getting/setting
- [x] Fragment getting/setting
- [x] Basic Redirect from empty path route
- [x] Imperative Navigation
- [x] Absolute/Relative Navigation
- [x] CanActivate Guard - Admin feature area
- [x] Lazy Loading
- [x] Location Strategy
- [x] Catch-all routes (Handling 404s)
- [x] Data Resolve
- [x] CanDeactivate Guard
- [x] Animating Route Transitions

Proposed topics for advanced chapter. The advanced chapter would have more of a cookbook approach with more focus on code samples.
- [ ] Route Tree traversal (Getting info from a parent route)
- [x] CanLoad Guard
- [x] CanActivateChild Guard
- [x] Component-Less Routes
- [ ] Secondary Routes
- [ ] Secondary Router Links
- [ ] Relative/Absolute Redirects
- [ ] Subscribing to Events (Errors, Loading Indicators)
- [ ] Router Outlet Events
- [ ] Debugging (Enable tracing)

cc: @wardbell @Foxandxss @DeborahK @bennadel @vsavkin

**Comment by chalin** [comment]
FYI, on the Dart side, we've broken down the Router guide into sections; e.g.: the [main router page](https://webdev.dartlang.org/angular/guide/router) leads to milestone pages, like this one for [milestone 1](https://webdev.dartlang.org/angular/guide/router/1). Each milestone page has a dropdown to help navigation (since the side nav has a limit on the depth of entries). We'll likely rework the guide again at some point soon. I like your topic breakdown above!

cc @kwalrath
