### ISSUE TITLE
Style Guide: Style 04-13

### ISSUE THREAD

**Issue by bampakoa** [angular/angular.io#1894]
I feel that in the case of routing the above rule is violated. Consider the following **app.routes.ts** file:

```
import { provideRouter, RouterConfig }  from '@angular/router';

import { crisisCenterRoutes }  from './crisis-center';

const routes: RouterConfig = [
    ...crisisCenterRoutes 
];

export const appRouterProviders = [
    provideRouter(routes)
];
```

The **crisisCenterRoutes** should be imported from **'./+crisis-center'** because crisis-center is a lazy loaded folder. But this contrasts with the style because the **app.routes.ts** file belongs to a parent folder of crisis center.

> Avoid allowing modules in sibling and parent folders to directly import a module in a lazy loaded feature.

**Comment by wardbell** [comment]
Actually ... it isn't lazy loaded. We'd like to make it lazy loaded someday soon, now that lazy loading is almost here (RC5). But it isn't yet so the code is correct.

We're also changing our position on the `+` prefix. We're softening from "do" to "consider" because there have been problem with servers that don't allow this prefix. And when we try something different (e.g., `_`), other servers don't like that. We can't find a prefix that works on all servers. And many of us don't think having a prefix is sufficiently compelling to overcome the grief.
