### ISSUE TITLE
autocomplete search for APIs broken in latest master

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#2054]
The autocomplete on the API docs overview page doesn't return any results when you run `check-deploy` with latest angular/angular master. It's fine if you build them from rc4.

![image](https://cloud.githubusercontent.com/assets/2286589/17501506/488671b8-5d94-11e6-9242-3fe7fa8b0d5c.png)

**Comment by naomiblack** [comment]
this was last working july 26. my best guess is that this is the commit that broke it? https://github.com/angular/angular.io/commit/cece720f47ede224a25ca0fe4063507edee6775c

**Comment by Foxandxss** [comment]
For some reason, this line makes it fail:

```
computePathsProcessor.pathTemplates.push({
  docTypes: ['api-list-data'],
  pathTemplate: 'api-list-audit.json',
  outputPathTemplate: '${path}'
});
```

**Comment by petebacondarwin** [comment]
The compute paths processor takes only one template to compute the path for each document type.

This new item overrides previous one for the `api-list-data` document type.

So the paths for the `api-list-data` is now written to `api-list-audit.json` rather than the previous `api-list.json`.

If you want to have two output files (`api-list-audit.json` and `api-list.json`) then you need two documents. Then you either need to give them different document types so that the path processor can distinguish between them, or add an extra field that is referenced in the path template.
