### ISSUE TITLE
Tutorial's "Report Issue" link opens angular issues instead of angular.io ones

### ISSUE THREAD

**Issue by diegotascon** [angular/angular.io#2124]
The "Report Issue" link at https://angular.io/docs/ts/latest/tutorial/toh-pt6.html (and previous), in the "Tour of Heroes" foot points to https://github.com/angular/angular/issues instead of https://github.com/angular/angular.io/issues.

**Comment by colinmorris** [comment]
This tripped me up as well. I had a feeling that the angular repo might not be the right place to file docs issues, but this repo isn't mentioned in the [Contributing](https://angular.io/contribute.html) page, and Angular's [CONTRIBUTING.md](https://github.com/angular/angular/blob/master/CONTRIBUTING.md) even says

> If you find a bug in the source code **or a mistake in the documentation**, you can help us by submitting an issue to our GitHub Repository.

Emphasis mine. I think this is meant to refer to the API documentation rather than Quickstart/Developer Guide etc. But it's all pretty confusing.

**Comment by Foxandxss** [comment]
Honestly, I am not sure if the link at the footer should point to angular or here, but the contributing.md has to be changed.

**Comment by Foxandxss** [comment]
Closing this since we are migrating to a new site and we will address this.
