### ISSUE TITLE
https://angular.io/docs/ts/latest/tutorial/toh-pt6.html snippet links are broken

### ISSUE THREAD

**Issue by VaughanJackson** [angular/angular.io#2213]
A number of snippet links from the Angular2 tour of heroes page https://angular.io/docs/ts/latest/tutorial/toh-pt6.html are broken. For example:

app/hero.service.ts (post)

BAD FILENAME: ../../../_fragments/toh-6/ts/app/hero.service-post.ts.md   Current path: docs,ts,latest,tutorial,toh-pt6 PathToDocs: ../../../

I raised this initially as https://github.com/angular/angular/issues/11127, but then Eric Martinez asked me to raise it in this issues repo. I noted an issues like this were previously opened and closed in the same angular issues repo - search issues for "BAD FILENAME".

**Comment by jzissu** [comment]
I noticed the same issue, and found the following in [https://github.com/angular/angular/issues/11148](https://github.com/angular/angular/issues/11148):

This one in particular is for the Post section of "Add, Edit, Delete" but there are instances of this all over the page from this point on. It looks like the reason for this is that the code has changed from the original and is now pointing at code that is no longer used. For example, for this Post section (and the Put and Save sections), the code that is shown in the overall file displayed later uses Create and Update methods which are never referenced in the tutorial, instead of Post/Put methods or a Save method which are all referenced there.

**Comment by mrobinet** [comment]
Looks like this may already be cleaned up, but not deployed yet? https://github.com/angular/angular.io/commit/907f848c95c306670b028eb113eec07fc6fd71b1#diff-dba43a2e28dc822997788284e58598db

@chalin

**Comment by chalin** [comment]
cc @kwalrath - it my be time for another deploy

**Comment by chalin** [comment]
@kwalrath - I'm surprise that there are any BAD FILENAME errors, since Travis tests for them and the build has been green for a while. I'm not sure what happened.

**Comment by kwalrath** [comment]
I'll deploy ASAP. (Which might be tomorrow, but I'll try for sooner.)

**Comment by kwalrath** [comment]
And... it's deployed.
