### ISSUE TITLE
`TypeError: Cannot read property 'baseName' of undefined` when linking to the lifecycle event dev guide

### ISSUE THREAD

**Issue by tbosch** [angular/angular.io#2294]
@petebacondarwin @IgorMinar When I want to link to the lifecycle event dev guide, I am getting the error below.

This is strange as other parts in our sources already refer to this guide successfully (see e.g. https://github.com/angular/angular/blob/master/modules/@angular/core/src/metadata.ts#L294).

Note: My links contain a `#` at the end, but the error is also present when I remove the `#`.

To reproduce: Clone [this PR](https://github.com/angular/angular/pull/11465) and replace `\@ with `@` in the file `lifecycle_hooks.ts`

```
TypeError: Cannot read property 'baseName' of undefined
    at Object._self.handler (/Users/tbosch/projects/angular.io/tools/api-builder/links-package/inline-tag-defs/linkDocs.js:49:76)
    at /Users/tbosch/projects/angular.io/node_modules/dgeni-packages/jsdoc/processors/inline-tags.js:229:41
```

**Comment by petebacondarwin** [comment]
The bug is in the linkDocs.js inline tag handler - it is making the assumption that a doc has a `fileInfo` property, which is not always true.

I also get problems with the `{@example ... }` tags if they contain a newline, which is a bug in the `example.js` inline tag handler code.

I will put together fixes for both

**Comment by petebacondarwin** [comment]
https://github.com/angular/angular.io/pull/2296 should solve your problems @tbosch

**Comment by tbosch** [comment]
Thanks, it did!
