### ISSUE TITLE
multiple aliases error on local build

### ISSUE THREAD

**Issue by ShaneCourtrille** [angular/angular.io#2543]
I'm receiving an error when I do gulp serve-and-sync after getting latest this morning.

Error: Only one of "stable" (or its aliases) allowed. There were 2 - doc "@angular/core/index/ContentChild" (type-alias)  - from file "C:/git/angular/modules/@angular/core/src/metadata/di.ts"

**Comment by Foxandxss** [comment]
Not happening for us. I highly recommend you to get a fresh copy of the repo because we made some important changes in the structure recently.

On the other hand, we highly recommend you to update the `angular` repo (that is where you are getting your error) or directly ignore the API part and use `gulp serve-and-sync-devguide`.

Cheers.
