### ISSUE TITLE
i18n dynamically change language

### ISSUE THREAD

**Issue by denkomanceski** [angular/angular.io#2689]
Is it possible to change the language of the app on the fly ? Based on the docs I can see that we need to compile the app for each language and than load the html for that language.. Is it possible for example to bind on some list dropdown a list of languages and dynamically change without having to reload the whole app? The ng-translate module supports this.

Thanks

**Comment by Irrelon** [comment]
@denkomanceski Did you close this because you found an answer? I am also interested to know the answer to this.

**Comment by boroda4436** [comment]
Here is one example https://stackoverflow.com/questions/39894394/angular2-i18n-language-switch, but I believe that there is another way to resolve this issue

**Comment by boroda4436** [comment]
Short anser: **we can’t!**
http://blog.danieleghidoli.it/2017/01/15/i18n-angular-cli-aot/

**Comment by Irrelon** [comment]
@boroda4436 Certainly it is possible, I could write my own module that works the same way as the AngularJS translate module did and have real-time text bindings so we can translate on the fly, but I'm guessing they went this route because changing languages usually only happens once in a user journey and after that is doesn't happen again because the user has selected the language they want, so on the fly is less useful.

This means that generating tons of bindings to do on the fly translation is wasteful and serves little purpose except during development where you want to check the translations are working without reloading the page.
