### ISSUE TITLE
Component input property - setter - more explicit information needed

### ISSUE THREAD

**Issue by michalboska** [angular/angular.io#2881]
I was having problem with Angular not recognizing the bound `@Input` property. It showed up that the error was only caused by the annotated setter occuring later in the code, than the unannotated getter.

I suggest making this requirement more explicit in https://angular.io/docs/ts/latest/cookbook/component-communication.html#!#parent-to-child-setter because this way it IMHO suggests, that annotating the **setter** is what's important here, not that the annotated method (getter or setter) must occur first, before the unannotated one.

**Comment by michalboska** [comment]
Original issue https://github.com/angular/angular/issues/13108

**Comment by wardbell** [comment]
See my comment on your angular/angular#13108 in which I investigated and determined that the problem is your compilation with a pre-release version of TypeScript.

I think that version of TypeScript has a bug and I should not compensate by dirtying the documentation with what is actually a misleading solution even if that solution is an effective workaround.

Let's also admit that this is a corner case.
