### ISSUE TITLE
ng-xi18n -p is not documented

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular.io#2909]
As per https://github.com/angular/angular-cli/issues/2201#issuecomment-263751025 
This command is not documented on the Angular site: https://angular.io/docs/ts/latest/cookbook/i18n.html

**Comment by vicb** [comment]
similar as `tsc -p` or `ngc -p` (ie path to the tsconfig)

**Comment by rolandoldengarm** [comment]
sure, but it should be documented somewhere, right? :)

**Comment by wardbell** [comment]
I'm looking at two issues related to i18n
https://github.com/angular/angular.io/issues/2909#issuecomment-263823918


I don't know how many options there are on `ng-xi18n`.   I **do know** that the Angular docs are **not** the place to enumerate every tool option any more than they are the place to enumerate every Angular API (you'll find [Angular API docs here](http://localhost:3000/docs/ts/latest/api/)).

The guide and cookbook docs are a place to learn about the main pathways through Angular, not every little detail.

We do supply details where they affect a significant part of the population. But I don't think chasing the `tsconfig` around the project folder structure is something we should teach.

If it is mentioned anywhere, it should be in the angular CLI docs, in response to your https://github.com/angular/angular-cli/issues/2201#issuecomment-263751025

Therefore, I'm closing this issue here in `angular.io`  as we have no intention of fixing it.
