### ISSUE TITLE
No way found to test the end to end functionality of a Component

### ISSUE THREAD

**Issue by vasuneetarya** [angular/angular.io#2988]
No way found to test the functionality of a Component which uses @angular/core viewContainerRef , elementRef, componentFactoryResolver etc. Document does not specified it completely. There are huge gapes in test cases. Please provide proper documentation or declare that angular component cannot be tested.

Regards
 Vasuneet Arya

**Comment by wardbell** [comment]
I understand your frustration in not finding an answer to your specific test case. But please be mindful of the code of conduct for this site. It asks you to avoid making sweeping negative generalizations of this kind.

What do you mean by "end to end functionality of a component"?
Would you please enumerate "the huge gaps" so we can consider addressing them.

TBH,  the  `viewContainerRef` is an advanced feature rarely found among Angular apps and, in our opinion, does not represent a "huge gap" in testing documentation.

If you submit an issue that provides a specific, trimmed down testing challenge, focused on a feature, I'd be happy to consider it.

I am closing this issue because of its tone and its lack of specificity.
