### ISSUE TITLE
Example is little strange

### ISSUE THREAD

**Issue by wKoza** [angular/angular.io#3036]
Hi,

While reading the guide "User Input", i read this template example : 

`
 <input #newHero (keyup.enter)="addHero(newHero.value)" 
(blur)="addHero(newHero.value); newHero.value="">
    <button (click)=addHero(newHero.value)>Add</button>
    <ul><li *ngFor="let hero of heroes">{{hero}}</li></ul>
`

It's little strange because the click event has no effect.  In fact, blur event is enough. So, for me, this button does not belong here.

**Comment by wardbell** [comment]
Yes, you're right. The button would be different if blur didn't clear the input value.

You're the first to have noticed this. Despite it's actually irrelevance, because this guide is about varieties of event binding, I'm inclined to keep the button for _pedagogical reasons_.

Do you see my point? Thanks.
