### ISSUE TITLE
Stylesheet Bindings not working for the dynamically created elements 

### ISSUE THREAD

**Issue by navneet10sep** [angular/angular.io#3061]
Dynamically created elements doesn't bind the stylesheet for the given class. Please see example below. I created `<div>` using the Renderer class and assigned the class name with all possible options setElementAttribute , setElementClass 
     
```
import { Component, ElementRef, Renderer, OnInit } from "@angular/core"

@Component({
  selector: 'viewport', 
  styleUrls: [ './viewport.style.css' ],
  templateUrl: './viewport.template.html'
})

export class Viewport {

       el: ElementRef;

	constructor(private renderer : Renderer, private element : ElementRef){
        this.el = element;
	}

	ngOnInit() { 
      let pageContainer = this.el.nativeElement.querySelector(".viewport-container-outter");
      let page = this.renderer.createElement(pageContainer,"div");
      this.renderer.setElementAttribute(page,"class","doc-page");
	}
}
```

viewport.style.css
```

.doc-page
{
	width: 1000px;
	height: 1200px;
	border: 1px solid #ccc;
	background: #fff;
	margin: 0 auto;
	display: block;
	margin-top: 10px;
	margin-bottom: 10px; 
}
```

viewport.template.html

```
<div class='viewport-container-outter' >
</div>
```

I also tried to achieve this with the document.createElement(), same problem persist 

      let page2 = document.createElement('div');
      page2.setAttribute("class","doc-page");
      pageContainer.appendChild(page2);
 

I can use the setElementStyle method as an alternative, that is working fine

**Comment by wardbell** [comment]
That's because the class is not called `doc-page` after Angular gets done mangling it to be local to the template. 

The best way to see what I mean is to add the `doc-page` class to your `ViewPort` component and inspect the DOM in the browser. You'll seen that Angular generates a special name.  I can't remember if the name is predictable enough for you to use inside your injected `<div>`.

The **real problem** is that **you're creating elements in the DOM by hand** inside your component. There is no way for Angular to know that you are doing this. Nor is that the "Angular" way to add dynamic content (a subject too big for this answer).

I am closing because this issue is unrelated to any of the documentation currently published.
