### ISSUE TITLE
Angular.IO test plunkrs not working

### ISSUE THREAD

**Issue by crh225** [angular/angular.io#3151]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I navigate to the link
https://angular.io/docs/ts/latest/guide/testing.html#!#live-examples

the only plunkrs that work have a check by them. Im using the latest version of chrome
![image](https://cloud.githubusercontent.com/assets/19475195/22340496/42bf03c6-e3b3-11e6-8e32-484183eea728.png)

**Expected behavior**

that the plunkrs work
**Minimal reproduction of the problem with instructions**

navigate to the appropriate links
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome

**Comment by AmyBlankenship** [comment]
Just to add to this, I get "no specs found" on the ones without checks beside them. I'd also like to note that it's impossible to bookmark these plunks and they quite frequently seem to just disappear and refreshing the tab doesn't fix it.

**Comment by Foxandxss** [comment]
@crh225 I don't see the problem. Can you be more specific? Those links goes to plunkers that does work for me.

@AmyBlankenship you need to save the plunkers to do that, they are created on the fly.

On the other hand, I see the "no specs found" issue.

**Comment by AmyBlankenship** [comment]
When you click the link, because it does a redirect you can't bookmark the link. You can't pause navigation to the redirection long enough to set the bookmark. I have a clipboard manager so I can always paste the link URL when I need to go to one of them, but not everyone knows to do that. It would be better if you could just bookmark it. Another possibility is to pull the links out to their own page so you don't have to dig through that mammoth testing page to find the links.

If you leave the plunker open for an extended period of time (like if you're trying to figure out this overly complicated framework by digging through a giant page on how to test various things), then it will go to something like "oops, this page was just here" with a "refresh the page" link. But because the parameters aren't passed in to the final page, refreshing the page doesn't buy you anything.

It's terrible UX to expect every user to create their own copy of the plunkers (which, by the way, also don't appear to be searchable) to access the real meat of the documentation on how to test.

**Comment by crh225** [comment]
I meant to report the:  I see the "no specs found" issue.

**Comment by crh225** [comment]
this is what I get on all of the links that don't have checks by them
![image](https://cloud.githubusercontent.com/assets/19475195/22480794/458599d6-e7b8-11e6-9fdc-7facad58a684.png)

**Comment by Foxandxss** [comment]
There is an error. I will fix.

**Comment by AmyBlankenship** [comment]
It doesn't seem to be fixed. Is it normal on the angular doc team to close bugs that are not yet fixed?

**Comment by Foxandxss** [comment]
Perhaps you should look at the last commit.

It is fixed in master, we go live in a scheduled manner so it is not immediately visible.

**Comment by crh225** [comment]
If you reference this issue in the commit message like most do, then it is easier to see that some type of work was completed.
