### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by Borquaye** [angular/angular.io#3232]
Source: 
https://angular.io/docs/ts/latest/testing/

The testing documentation states "newEvent" in multiple locations as opposed to "new Event" 
Example:
`page.nameInput.dispatchEvent(newEvent('input'));`

Should be:
`page.nameInput.dispatchEvent(new Event('input'));`

Looks like a copy paste error.

**Comment by realappie** [comment]
I have a feeling its not an error, because its also getting imported as newEvent. If it were to be a class named `event` and imported like so. I would have understood the new operator is being used. But I have a feeling thats not the case after looking at these three different imports
[First](https://github.com/angular/angular.io/blob/f24b830c8a69eb109e7bfec6508208006ef7ac5c/public/docs/_examples/testing/ts/src/app/hero/hero-detail.component.spec.ts#L10), [Second](https://github.com/angular/angular.io/blob/1101f07ef2d41f1b520c76095529f45973ba7051/public/docs/_examples/testing/ts/src/app/shared/highlight.directive.spec.ts#L6), [third](https://github.com/angular/angular.io/blob/1101f07ef2d41f1b520c76095529f45973ba7051/public/docs/_examples/testing/ts/src/app/bag/bag.spec.ts#L29)

**Comment by Foxandxss** [comment]
As @realappie said. Yeah, it is `newEvent`.

**Comment by PrimeByDesign** [comment]
Hello all, 

It would be really helpful if you would show the imports in your documentation for this. @Borquaye and I do not know where to import newEvent from.
