### ISSUE TITLE
Quickstart documentation minor issue 

### ISSUE THREAD

**Issue by mcpDESIGNS** [angular/angular.io#324]
Very minor issue, I just couldn't see where / how to edit the Quickstart documentation.
I can make do a PR to update it if someone can assign it to me?

Right now it states:

There is also a scripts section. Find and replace it with the following:

    {
      "scripts": {
       "start": "live-server"
       }
    }
It should be changed to the below line, otherwise npm start errors out with a parse JSON error since the package.json isn't valid JSON.

    "scripts": {
        "start": "live-server"
     }

If there's an easy way/place to make a PR about this I'll do it just let me know!

**Comment by wardbell** [comment]
That is an artifact of the tool that generates this snippet. I'm making this an issue for the person responsible for tooling.  Thanks for pointing it out.

**Comment by mcpDESIGNS** [comment]
Not a problem, glad to help out (even for something this minor) @wardbell

**Comment by michaelrommel** [comment]
I have a smiliar small issue, it seems to me, the white-on-blue box heading in the 5min quickstart should read "app/app.component.ts (export)" instead of "app/component.ts (export)"

Any better way to report these minor things? Can we just use this issue for it or should we open up new ones or just skip this small things, as certainly the devs have major issues to tend...

**Comment by michaelrommel** [comment]
OK, it has been fixed already.
