### ISSUE TITLE
Contradiction in "HIERARCHICAL DEPENDENCY INJECTORS" Section

### ISSUE THREAD

**Issue by justinwilaby** [angular/angular.io#3242]
In the [HIERARCHICAL DEPENDENCY INJECTORS](https://angular.io/docs/ts/latest/guide/hierarchical-dependency-injection.html) section, the text: 

> An Angular application is a tree of components. Each component instance has its own injector! The tree of components parallels the tree of injectors.

is contradicted in the immediate paragraph that follows: 

> Angular doesn't actually create a separate injector for each component. Every component doesn't need its own injector and it would be horribly inefficient to create masses of injectors for no good purpose.

Do Components have their *own* injectors or don't they?  The term **own injector** is confounded with the term **an injector** and should be clarified.

**Comment by Foxandxss** [comment]
I can be mistaken in the details in here, but the idea is that each component can have their own injection, but that doesn't meant that that injector is always created but only when you actually use it.

So a normal component won't create a new one, but if you set `providers` on it, it will.

**Comment by justinwilaby** [comment]
Let's read these 2 sentences as if they were side by side:

> Each component instance has its own injector! Angular doesn't actually create a separate injector for each component.

It's a direct contradiction. Any English teacher would fail a student if this were used in their final thesis. The documents should provide better clarity.

**Comment by Foxandxss** [comment]
We are open for improvements my friend. Please send a PR.

**Comment by wardbell** [comment]
I see your point and agree that the text can be improved. However, it is not contradictory and those two sentences are bridged by an explanation that breaks the apparent contradiction ... a bridge that you break when you jam them side-by-side.

The mental model: every component _has_ its own injector.  You will always experience it that way. That's what the first sentence means.

Under the hood is often a proxy to the actual injector (which has a reference to the real one which may ... and probably is ...shared). There is only a need to create a real injector when you _provide_ a service at that level. Otherwise, Angular proxies up to the root. That's what the second sentence means.

Maybe we should have said it that way. We probably shouldn't say _anything_ about it because it's an implementation detail that has no consequences for the developer. 

We will leave this issue open until we correct the prose, one way or the other.

I'd like to take a moment to speak to you about how you framed your issue. Perhaps you are unaware that it came across as argumentative. The bit about "any English teacher would fail a student" is disrespectful and contrary to our Code of Conduct. Please keep the feedback coming but temper your language a bit.  We humans will respond better when you do.
