### ISSUE TITLE
live test example on Angular.io not working

### ISSUE THREAD

**Issue by crh225** [angular/angular.io#3390]
When navigating to any of the live test examples on angular.io, all plunkrs with blue underlines have quite a few test failures.

![image](https://cloud.githubusercontent.com/assets/19475195/24072960/417d5652-0bbd-11e7-963c-3ed25872ec49.png)

![image](https://cloud.githubusercontent.com/assets/19475195/24072946/0891bc20-0bbd-11e7-9552-2381a2168695.png)

**Comment by Foxandxss** [comment]
Thanks, there is a pr to fix them, I need to rebase it.

**Comment by acdcjunior** [comment]
@Foxandxss I notice the plnkr (live example) at the HTTP part of the tutorial (https://angular.io/docs/ts/latest/tutorial/toh-pt6.html) (direct link to plnkr: https://angular.io/resources/live-examples/toh-6/ts/eplnkr.html) is not working as well.

The problem is related to the `basePath.substr(1)` at the `systemjs-angular-loader.js` (at this line https://github.com/angular/angular.io/blob/e6741efd8f4fad20ca519d8eb99ec0c7d102577d/public/docs/_examples/_boilerplate/src/systemjs-angular-loader.js#L33) which makes everything work when we remove `.substr(1)` there.

Does the PR you mention (I couldn't find it) address this?

**Comment by Foxandxss** [comment]
No, that is something I am fixing right now.

**Comment by acdcjunior** [comment]
@Foxandxss Okay, but you are aware of the one I'm mentioning, right?

**Comment by Foxandxss** [comment]
The other one seems like I merged it already. But tests are failing is now due the other error.
