### ISSUE TITLE
In Dart QS: angular2-getting-started -> angular2_getting_started

### ISSUE THREAD

**Issue by kwalrath** [angular/angular.io#378]
Dart style is to use _s in names, not -s.

Visible in http://localhost:3000/docs/dart/latest/quickstart.html, source files presumably pulled in from _examples directory.

**Comment by chalin** [comment]
While the original problem reported by this issue seems to be gone, we still name the project folder as `angular2-quickstart`. Maybe it should be `angular2_quickstart`, or better yet, just `quickstart`, thus matching the [angular-examples](https://github.com/angular-examples) project name.

Whatever we decide, the name should match that given in the `pubspec.yaml`.

**Comment by chalin** [comment]
Actually, if we follow what is used for the Tour of Heroes, then the name `angular2_quickstart` is what is most appropriate. Opting for that.

**Comment by kwalrath** [comment]
Thanks!
