### ISSUE TITLE
Update TS router example + text to use a selector

### ISSUE THREAD

**Issue by kwalrath** [angular/angular.io#676]
See https://github.com/angular/angular/issues/6146.

**Comment by kasperpeulen** [comment]
![image](https://cloud.githubusercontent.com/assets/1035299/12426803/f735455c-bedb-11e5-96b7-db6d265e5fb7.png)

it now makes an `undefined` element in the typescript example

**Comment by wardbell** [comment]
See also my comment to [angular/angular#1662](https://github.com/angular/angular/issues/1662) where I  object vigorously to a required `selector:`.

The compiler should be fixed to create a `<div>` not an `<undefined>`.

FWIW, `<undefined>` is unappealing but harmless, right?  So why are we pressing this issue?

**Comment by kasperpeulen** [comment]
@wardbell 

To get some history here. I first created an issue, because I was porting the router guide to Dart, but in Dart we don't get this `undefined` element, there is just a blank screen with an error.

Then, @tbosch said, that this is not supposed to work in typescript or in Dart, and therefore we created this issue.

So, if this is now supposed to work again (which I agree on), we still have the issue that it doesn't work in Dart :) And I would like the Dart routing guide to be straight port from typescript.

**Comment by wardbell** [comment]
Oh this is so sad :(

It really *should* work.  Curiously, why does Dart freak out? Is it the presence of the `<undefined>` element ... which browses simply ignore.

I'd rather that you add a selector to the Dart version, but I'm prepared to add a selector to the TS version to get you out of a jam. It will only confuse a few readers.

**Comment by kasperpeulen** [comment]
> I'd rather that you add a selector to the Dart version,

Okay, I will do that for now then. Shall I use `div` then?

**Comment by wardbell** [comment]
Is this resolved in angular.io?  I'm not talking about whether it has been fixed in Angular.
