### ISSUE TITLE
Documentation links beginning with 'angular2' produce imcomplete filepaths

### ISSUE THREAD

**Issue by brycepj** [angular/angular.io#704]
Documentation link paths beginning with 'angular2' ( e.g. `{@link angular2/**}` ) are not properly appending file extensions (*.html) to hrefs in the DOM, resulting in 404's. 

The remaining usages of 'angular2' path I see are `angular2/di/OpaqueToken` and `angular2/lifecycle_hooks`. They are referenced in the following files:

angular/modules/angular2/src/core/...
- di/provider.ts
- metadata/directives.ts
- metadata.ts
- application_tokens.ts

I spent some time trying to pinpoint where extensions are fixed, but I'm not that familiar with the build. I'll look into this a bit later, unless someone can shed some light on this in the meantime.

**Comment by wardbell** [comment]
You are correct that some of these mistakes pepper the code. We fix them when we find them. Also, these are defects in `angular/angular`, not `angular.io` so they won't be discovered or fixed by the responsible team.  You might want to post there.

I'm closing your issue for now because we can't act on it. We'll hold open any that you specifically identify.
