### ISSUE TITLE
Why are we stopping event propagation?

### ISSUE THREAD

**Issue by btford** [angular/angular.io#86]
For instance:
* https://github.com/angular/angular.io/blob/master/public/about/index.jade#L30
* https://github.com/angular/angular.io/blob/master/public/resources/js/site.js#L35-L50

**Comment by alexwolfe** [comment]
Clicking the bio card opens the bio modal. If we don't stop the event prop on this social links the bio card pops up momentarily and then the browser gets directed to the person's twitter/website which is not the desired behavior. 

The events on the toggle are unnecessary since we are using buttons not anchor tags, removing in my outstanding branch. Good catch here.
