### ISSUE TITLE
Docs with javascript?

### ISSUE THREAD

**Issue by FrancescoMussi** [angular/angular.io#919]
Hi guys!
Do you plan to write the documentation for Angular 2 also in javascript besides typescript?

I think the aim of documentation is to explain to the widest range of user possible.
A documentation with javascript would help to reach that aim.
Otherwise it add a degree of complexity for who doesn't know typescript and is just eager to learn Angular 2.

Thank you for the attention!

**Comment by tilwinjoy** [comment]
Not sure why you closed this without any response... I'm wondering the same...

**Comment by Foxandxss** [comment]
@tilwinjoy we hear you, there is no need of responding to every issue on the repo about that.

Thanks.

**Comment by tilwinjoy** [comment]
According to your [comment here](https://github.com/angular/angular.io/issues/2989#issuecomment-268568063) that issue was specific to API documentation. And I was told to open an issue in this repo. As per my knowledge it's not encouraged to blindly open new issues without searching for existing ones. 

I don't see an "open" issue related to JavaScript documentation, or a closed issue with a proper yes/no/in-progress response at the time. Hence asking the op if they found an answer somewhere else or is going to re-open this without me creating another duplicate, which would be even more annoying. Sorry if it was still annoying.

BTW if someone's looking for this #2930 seems to be some kind of roadmap
