### ISSUE TITLE
EXCEPTION: No value accessor for ''

### ISSUE THREAD

**Issue by realdope** [angular/angular.io#990]
Hi, I am close-minded and I am not interested in Typescript. I've been trying to get started on this simple example.
```javascript
(function(app) {
  app.comp = ng.core.Component({
    selector: 'div[ng]',
    template: '<h1>Hello {{obj.a}}</h1>' + 
      '<div><input type="text" [(ngModel)]="obj.a"/></div>',
  }).Class({
    constructor: function() {
      this.obj = {a: "World"};
    }
  });
})(window.app || (window.app={}));
```

It works with 2.0.0-beta.0. When I run it against beta.1 to beta.11, the code breaks and I get EXCEPTION: No value accessor for '' in [obj.a in class0@0:48].

If I want to use simple map values instead of the prototyped objects that Typescript enforces, how do I do that with the latest versions?

**Comment by wardbell** [comment]
Please only file documentation issues here. Yours is a support question which is better placed on StackOverflow.  That's why I'm closing it.

But ... because I was curious ... I modified the QuickStart plunker to align with your code and this works:
```javascript
(function(app) {
  app.AppComponent =  ng.core.Component({
      selector: 'my-app',
      template: '<h1>Hello {{obj.a}}</h1>'+ 
      '<div><input type="text" [(ngModel)]="obj.a"/></div>'
    })
    .Class({
      constructor: function() {
         this.obj = {a: "World"};
      }
    });
})(window.app || (window.app = {}));
```
The only differences I see are (a) the selector and (b) the name of the component. 

(a) Why did you write: `'div[ng]`?  You didn't show your `index.html` so it's difficult to see how this does or does not match the application start tag there.

(b) You don't show your `main.ts` so can't see how you bootstrap. I suspect that you aren't importing and bootstrapping with `app.comp`.  **I reproduce your error when I misalign the component name.**

**Comment by realdope** [comment]
Hi, thank you for your response. I admit perhaps it should have been on Stack Overflow instead, but I suspected it to be an error because it gets produced by changing code version. I followed your change and I'm still producing the same error. Below is the entire code. Changing the scripts to 2.0.0-beta.0 would fix the error.

```javascript
<!doctype html>
<html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.11/angular2-polyfills.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.11/Rx.umd.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.11/angular2-all.umd.min.js"></script>
<script>

(function(app) {
  app.AppComponent =  ng.core.Component({
      selector: 'my-app',
      template: '<h1>Hello {{obj.a}}</h1>'+ 
      '<div><input type="text" [(ngModel)]="obj.a"/></div>'
    })
    .Class({
      constructor: function() {
         this.obj = {a: "World"};
      }
    });
})(window.app || (window.app = {}));

(function(app) {
  document.addEventListener('DOMContentLoaded', function() {
    ng.platform.browser.bootstrap(app.AppComponent);
  });
})(window.app || (window.app={}));
</script>

<body>
<my-app></my-app>

</body>

</html>
```javascript
